// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatController from "./chat_controller"
application.register("chat", ChatController)

import DownloadController from "./download_controller"
application.register("download", DownloadController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import FormController from "./form_controller"
application.register("form", FormController)

import HuntController from "./hunt_controller"
application.register("hunt", HuntController)

import MessageController from "./message_controller"
application.register("message", MessageController)

import NavController from "./nav_controller"
application.register("nav", NavController)

import PastHuntsController from "./past_hunts_controller"
application.register("past-hunts", PastHuntsController)

import SubmissionController from "./submission_controller"
application.register("submission", SubmissionController)

import TimerController from "./timer_controller"
application.register("timer", TimerController)
