// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import FlashController from "./flash_controller.js"
application.register("flash", FlashController)

import FormController from "./form_controller.js"
application.register("form", FormController)

import HuntController from "./hunt_controller.js"
application.register("hunt", HuntController)

import NavController from "./nav_controller.js"
application.register("nav", NavController)

import PastHuntsController from "./past_hunts_controller.js"
application.register("past-hunts", PastHuntsController)

import SubmissionController from "./submission_controller.js"
application.register("submission", SubmissionController)
