// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HuntController from "./hunt_controller"
application.register("hunt", HuntController)

import SubmissionController from "./submission_controller"
application.register("submission", SubmissionController)

import NavController from "./nav_controller"
application.register("nav", NavController)
